name: Deploy — Extractor Cron (Gen2)

on:
  push:
    branches: [ main ]
    paths:
      - 'extractor_cron.py'
      - 'requirements_extractor_cron.txt'
      - '.github/workflows/deploy-extractor-cron.yml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  REGION: ${{ vars.REGION }}                # e.g., us-central1
  WORKLOAD_IDENTITY_PROVIDER: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
  DEPLOYER_SA: ${{ vars.DEPLOYER_SA }}      # SA with deploy perms
  RUNTIME_SA: ${{ vars.RUNTIME_SA }}        # SA the function runs as (has Storage + Vertex perms)
  SCHEDULER_SA: ${{ vars.SCHEDULER_SA }}    # SA used by Cloud Scheduler to invoke function
  GCS_BUCKET: ${{ vars.GCS_BUCKET }}
  OUTPUT_PREFIX: craigslist
  FUNCTION_NAME: extractor-cron
  JOB_ID: extract-hourly                     # hourly job id
  CRON: '0 * * * *'                          # hourly
  TIMEZONE: 'America/New_York'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.DEPLOYER_SA }}
          project_id: ${{ env.PROJECT_ID }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Enable required services (idempotent)
        run: |
          gcloud services enable \
            cloudfunctions.googleapis.com \
            run.googleapis.com \
            artifactregistry.googleapis.com \
            cloudscheduler.googleapis.com \
            aiplatform.googleapis.com

      - name: Stage src
        run: |
          rm -rf cron_src
          mkdir -p cron_src
          cp extractor_cron.py cron_src/main.py
          cp requirements_extractor_cron.txt cron_src/requirements.txt

      - name: Deploy function (Gen2, py312, 1Gi, 540s, Vertex OFF)
        run: |
          gcloud functions deploy "$FUNCTION_NAME" \
            --gen2 \
            --region="${{ env.REGION }}" \
            --runtime=python312 \
            --entry-point=extract_http \
            --trigger-http \
            --service-account="${{ env.RUNTIME_SA }}" \
            --no-allow-unauthenticated \
            --timeout=540s \
            --memory=1Gi \
            --max-instances=1 \
            --source=./cron_src \
            --set-env-vars="PROJECT_ID=${{ env.PROJECT_ID }},LOCATION=${{ env.REGION }},GCS_BUCKET=${{ env.GCS_BUCKET }},OUTPUT_PREFIX=${{ env.OUTPUT_PREFIX }},LOG_EXECUTION_ID=true,USE_VERTEX=0"

      - name: Get URL
        id: fn
        run: |
          URL="$(gcloud functions describe "$FUNCTION_NAME" --region="${{ env.REGION }}" --format='value(serviceConfig.uri)')"
          echo "FUNCTION_URL=$URL" >> "$GITHUB_OUTPUT"

      - name: Allow Scheduler SA to invoke
        run: |
          gcloud run services add-iam-policy-binding "$FUNCTION_NAME" \
            --region="${{ env.REGION }}" \
            --member="serviceAccount:${{ env.SCHEDULER_SA }}" \
            --role="roles/run.invoker" || true

      - name: Create/Update hourly scheduler
        run: |
          set -euo pipefail
          if gcloud scheduler jobs describe "$JOB_ID" --location="${{ env.REGION }}" >/dev/null 2>&1; then
            gcloud scheduler jobs update http "$JOB_ID" \
              --location="${{ env.REGION }}" \
              --schedule="${{ env.CRON }}" \
              --time-zone="${{ env.TIMEZONE }}" \
              --http-method=POST \
              --uri="${{ steps.fn.outputs.FUNCTION_URL }}" \
              --oidc-service-account-email="${{ env.SCHEDULER_SA }}" \
              --oidc-token-audience="${{ steps.fn.outputs.FUNCTION_URL }}" \
              --update-headers="Content-Type=application/json" \
              --message-body='{"max_files":200,"overwrite":false}'
          else
            gcloud scheduler jobs create http "$JOB_ID" \
              --location="${{ env.REGION }}" \
              --schedule="${{ env.CRON }}" \
              --time-zone="${{ env.TIMEZONE }}" \
              --http-method=POST \
              --uri="${{ steps.fn.outputs.FUNCTION_URL }}" \
              --oidc-service-account-email="${{ env.SCHEDULER_SA }}" \
              --oidc-token-audience="${{ steps.fn.outputs.FUNCTION_URL }}" \
              --headers="Content-Type=application/json" \
              --message-body='{"max_files":200,"overwrite":false}'
          fi
